In [1]:
import pandas as pd


In [2]:
df = pd.read_csv('BMW_Car_Sales_Classification.csv') 

In [3]:
df


Model  Year         Region   Color Fuel_Type Transmission  \
0      5 Series  2016           Asia     Red    Petrol       Manual   
1            i8  2013  North America     Red    Hybrid    Automatic   
2      5 Series  2022  North America    Blue    Petrol    Automatic   
3            X3  2024    Middle East    Blue    Petrol    Automatic   
4      7 Series  2020  South America   Black    Diesel       Manual   
...         ...   ...            ...     ...       ...          ...   
49995        i3  2014           Asia     Red    Hybrid       Manual   
49996        i3  2023    Middle East  Silver  Electric       Manual   
49997  5 Series  2010    Middle East     Red    Petrol    Automatic   
49998        i3  2020           Asia   White  Electric    Automatic   
49999        X1  2020  North America    Blue    Diesel       Manual   

       Engine_Size_L  Mileage_KM  Price_USD  Sales_Volume Sales_Classification  
0                3.5      151748      98740          8300                 High  
1                1.6      121671      79219          3428                  Low  
2                4.5       10991     113265          6994                  Low  
3                1.7       27255      60971          4047                  Low  
4                2.1      122131      49898          3080                  Low  
...              ...         ...        ...           ...                  ...  
49995            4.6      151030      42932          8182                 High  
49996            4.2      147396      48714          9816                 High  
49997            4.5      174939      46126          8280                 High  
49998            3.8        3379      58566          9486                 High  
49999            3.3      171003      77492          1764                  Low  

[50000 rows x 11 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Model                 50000 non-null  object 
 1   Year                  50000 non-null  int64  
 2   Region                50000 non-null  object 
 3   Color                 50000 non-null  object 
 4   Fuel_Type             50000 non-null  object 
 5   Transmission          50000 non-null  object 
 6   Engine_Size_L         50000 non-null  float64
 7   Mileage_KM            50000 non-null  int64  
 8   Price_USD             50000 non-null  int64  
 9   Sales_Volume          50000 non-null  int64  
 10  Sales_Classification  50000 non-null  object 
dtypes: float64(1), int64(4), object(6)
memory usage: 4.2+ MB


In [5]:
df["Sales_Classification"].unique()

array(['High', 'Low'], dtype=object)

In [6]:
mapping = {"High":1, "Low":0}
df["Sales_Classification"] = df["Sales_Classification"].map(mapping)

In [7]:
df

Model  Year         Region   Color Fuel_Type Transmission  \
0      5 Series  2016           Asia     Red    Petrol       Manual   
1            i8  2013  North America     Red    Hybrid    Automatic   
2      5 Series  2022  North America    Blue    Petrol    Automatic   
3            X3  2024    Middle East    Blue    Petrol    Automatic   
4      7 Series  2020  South America   Black    Diesel       Manual   
...         ...   ...            ...     ...       ...          ...   
49995        i3  2014           Asia     Red    Hybrid       Manual   
49996        i3  2023    Middle East  Silver  Electric       Manual   
49997  5 Series  2010    Middle East     Red    Petrol    Automatic   
49998        i3  2020           Asia   White  Electric    Automatic   
49999        X1  2020  North America    Blue    Diesel       Manual   

       Engine_Size_L  Mileage_KM  Price_USD  Sales_Volume  \
0                3.5      151748      98740          8300   
1                1.6      121671      79219          3428   
2                4.5       10991     113265          6994   
3                1.7       27255      60971          4047   
4                2.1      122131      49898          3080   
...              ...         ...        ...           ...   
49995            4.6      151030      42932          8182   
49996            4.2      147396      48714          9816   
49997            4.5      174939      46126          8280   
49998            3.8        3379      58566          9486   
49999            3.3      171003      77492          1764   

       Sales_Classification  
0                         1  
1                         0  
2                         0  
3                         0  
4                         0  
...                     ...  
49995                     1  
49996                     1  
49997                     1  
49998                     1  
49999                     0  

[50000 rows x 11 columns]

In [8]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
class DataPreprocessing:
    def __init__(self, df):
        self.df = df 
        
        

    def tozala(self):
        for col in self.df.columns:
            if self.df[col].isnull().any():
                if self.df[col].dtype == 'object':
                    self.df[col] = self.df[col].fillna(self.df[col].mode()[0])
                else:
                    self.df[col] = self.df[col].fillna(self.df[col].mean())
        return self

    def encodla(self):
        self.encoder = LabelEncoder()
        for col in self.df.columns:
            if self.df[col].dtype == 'object':
                if self.df[col].nunique() <= 6:
                    dummies = pd.get_dummies(self.df[col], prefix=col, dtype=int)
                    self.df = pd.concat([self.df.drop(columns=[col]), dummies], axis=1)
                else:
                    self.df[col] = self.encoder.fit_transform(self.df[col])
        return self

    def scaling_qil(self):
        self.scaler = StandardScaler()
        numeric_cols = self.df.select_dtypes(include=['int64', 'float64']).columns.drop("Sales_Classification")
        self.df[numeric_cols] = self.scaler.fit_transform(self.df[numeric_cols])
        return self
     

    def get_df(self):
        return self.df

In [9]:
prep = DataPreprocessing(df)
prep.tozala().encodla().scaling_qil()
cleaned_df=prep.get_df()

In [10]:
cleaned_df

Model      Year  Engine_Size_L  Mileage_KM  Price_USD  Sales_Volume  \
0     -1.258064 -0.234876       0.250548    0.887814   0.911817      1.131530   
1      1.575953 -0.928611      -1.632377    0.368717   0.160951     -0.573911   
2     -1.258064  1.152595       1.241561   -1.541504   1.470514      0.674365   
3      0.316390  1.615085      -1.533276   -1.260805  -0.540950     -0.357231   
4     -0.943173  0.690105      -1.136871    0.376656  -0.966867     -0.695729   
...         ...       ...            ...         ...        ...           ...   
49995  1.261062 -0.697366       1.340662    0.875423  -1.234811      1.090224   
49996  1.261062  1.383840       0.944257    0.812704  -1.012409      1.662205   
49997 -1.258064 -1.622346       1.241561    1.288067  -1.111955      1.124529   
49998  1.261062  0.690105       0.547852   -1.672880  -0.633457      1.546689   
49999  0.001499  0.690105       0.052345    1.220136   0.094523     -1.156394   

       Sales_Classification  Region_Africa  Region_Asia  Region_Europe  ...  \
0                         1      -0.444624     2.216836      -0.447235  ...   
1                         0      -0.444624    -0.451093      -0.447235  ...   
2                         0      -0.444624    -0.451093      -0.447235  ...   
3                         0      -0.444624    -0.451093      -0.447235  ...   
4                         0      -0.444624    -0.451093      -0.447235  ...   
...                     ...            ...          ...            ...  ...   
49995                     1      -0.444624     2.216836      -0.447235  ...   
49996                     1      -0.444624    -0.451093      -0.447235  ...   
49997                     1      -0.444624    -0.451093      -0.447235  ...   
49998                     1      -0.444624     2.216836      -0.447235  ...   
49999                     0      -0.444624    -0.451093      -0.447235  ...   

       Color_Grey  Color_Red  Color_Silver  Color_White  Fuel_Type_Diesel  \
0       -0.447686   2.215417     -0.447750    -0.446269         -0.570052   
1       -0.447686   2.215417     -0.447750    -0.446269         -0.570052   
2       -0.447686  -0.451382     -0.447750    -0.446269         -0.570052   
3       -0.447686  -0.451382     -0.447750    -0.446269         -0.570052   
4       -0.447686  -0.451382     -0.447750    -0.446269          1.754225   
...           ...        ...           ...          ...               ...   
49995   -0.447686   2.215417     -0.447750    -0.446269         -0.570052   
49996   -0.447686  -0.451382      2.233388    -0.446269         -0.570052   
49997   -0.447686   2.215417     -0.447750    -0.446269         -0.570052   
49998   -0.447686  -0.451382     -0.447750     2.240802         -0.570052   
49999   -0.447686  -0.451382     -0.447750    -0.446269          1.754225   

       Fuel_Type_Electric  Fuel_Type_Hybrid  Fuel_Type_Petrol  \
0               -0.576457         -0.584002          1.727444   
1               -0.576457          1.712324         -0.578890   
2               -0.576457         -0.584002          1.727444   
3               -0.576457         -0.584002          1.727444   
4               -0.576457         -0.584002         -0.578890   
...                   ...               ...               ...   
49995           -0.576457          1.712324         -0.578890   
49996            1.734734         -0.584002         -0.578890   
49997           -0.576457         -0.584002          1.727444   
49998            1.734734         -0.584002         -0.578890   
49999           -0.576457         -0.584002         -0.578890   

       Transmission_Automatic  Transmission_Manual  
0                   -0.993859             0.993859  
1                    1.006179            -1.006179  
2                    1.006179            -1.006179  
3                    1.006179            -1.006179  
4                   -0.993859             0.993859  
...                       ...                  ...  
49995      

In [11]:
cleaned_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Model                   50000 non-null  float64
 1   Year                    50000 non-null  float64
 2   Engine_Size_L           50000 non-null  float64
 3   Mileage_KM              50000 non-null  float64
 4   Price_USD               50000 non-null  float64
 5   Sales_Volume            50000 non-null  float64
 6   Sales_Classification    50000 non-null  int64  
 7   Region_Africa           50000 non-null  float64
 8   Region_Asia             50000 non-null  float64
 9   Region_Europe           50000 non-null  float64
 10  Region_Middle East      50000 non-null  float64
 11  Region_North America    50000 non-null  float64
 12  Region_South America    50000 non-null  float64
 13  Color_Black             50000 non-null  float64
 14  Color_Blue              50000 non-null

In [12]:
cleaned_df.to_csv('DataPreprocessing.csv', index=False)


In [13]:
df = pd.read_csv('DataPreprocessing.csv')

In [14]:
df

Model      Year  Engine_Size_L  Mileage_KM  Price_USD  Sales_Volume  \
0     -1.258064 -0.234876       0.250548    0.887814   0.911817      1.131530   
1      1.575953 -0.928611      -1.632377    0.368717   0.160951     -0.573911   
2     -1.258064  1.152595       1.241561   -1.541504   1.470514      0.674365   
3      0.316390  1.615085      -1.533276   -1.260805  -0.540950     -0.357231   
4     -0.943173  0.690105      -1.136871    0.376656  -0.966867     -0.695729   
...         ...       ...            ...         ...        ...           ...   
49995  1.261062 -0.697366       1.340662    0.875423  -1.234811      1.090224   
49996  1.261062  1.383840       0.944257    0.812704  -1.012409      1.662205   
49997 -1.258064 -1.622346       1.241561    1.288067  -1.111955      1.124529   
49998  1.261062  0.690105       0.547852   -1.672880  -0.633457      1.546689   
49999  0.001499  0.690105       0.052345    1.220136   0.094523     -1.156394   

       Sales_Classification  Region_Africa  Region_Asia  Region_Europe  ...  \
0                         1      -0.444624     2.216836      -0.447235  ...   
1                         0      -0.444624    -0.451093      -0.447235  ...   
2                         0      -0.444624    -0.451093      -0.447235  ...   
3                         0      -0.444624    -0.451093      -0.447235  ...   
4                         0      -0.444624    -0.451093      -0.447235  ...   
...                     ...            ...          ...            ...  ...   
49995                     1      -0.444624     2.216836      -0.447235  ...   
49996                     1      -0.444624    -0.451093      -0.447235  ...   
49997                     1      -0.444624    -0.451093      -0.447235  ...   
49998                     1      -0.444624     2.216836      -0.447235  ...   
49999                     0      -0.444624    -0.451093      -0.447235  ...   

       Color_Grey  Color_Red  Color_Silver  Color_White  Fuel_Type_Diesel  \
0       -0.447686   2.215417     -0.447750    -0.446269         -0.570052   
1       -0.447686   2.215417     -0.447750    -0.446269         -0.570052   
2       -0.447686  -0.451382     -0.447750    -0.446269         -0.570052   
3       -0.447686  -0.451382     -0.447750    -0.446269         -0.570052   
4       -0.447686  -0.451382     -0.447750    -0.446269          1.754225   
...           ...        ...           ...          ...               ...   
49995   -0.447686   2.215417     -0.447750    -0.446269         -0.570052   
49996   -0.447686  -0.451382      2.233388    -0.446269         -0.570052   
49997   -0.447686   2.215417     -0.447750    -0.446269         -0.570052   
49998   -0.447686  -0.451382     -0.447750     2.240802         -0.570052   
49999   -0.447686  -0.451382     -0.447750    -0.446269          1.754225   

       Fuel_Type_Electric  Fuel_Type_Hybrid  Fuel_Type_Petrol  \
0               -0.576457         -0.584002          1.727444   
1               -0.576457          1.712324         -0.578890   
2               -0.576457         -0.584002          1.727444   
3               -0.576457         -0.584002          1.727444   
4               -0.576457         -0.584002         -0.578890   
...                   ...               ...               ...   
49995           -0.576457          1.712324         -0.578890   
49996            1.734734         -0.584002         -0.578890   
49997           -0.576457         -0.584002          1.727444   
49998            1.734734         -0.584002         -0.578890   
49999           -0.576457         -0.584002         -0.578890   

       Transmission_Automatic  Transmission_Manual  
0                   -0.993859             0.993859  
1                    1.006179            -1.006179  
2                    1.006179            -1.006179  
3                    1.006179            -1.006179  
4                   -0.993859             0.993859  
...                       ...                  ...  
49995      

In [15]:
x = df.drop("Sales_Classification",axis=1)
y = df["Sales_Classification"]

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
x_train, x_temp, y_train, y_temp = train_test_split(x,y,test_size = 0.2, random_state=42)
x_val, x_test, y_val, y_test = train_test_split(x_temp, y_temp, test_size = 0.5,random_state=42)

In [18]:
from sklearn.linear_model import LogisticRegression
logistic_model = LogisticRegression()

In [19]:
logistic_model

LogisticRegression()

In [20]:
logistic_model.fit(x_train, y_train)

LogisticRegression()

In [21]:
logistic_pred = logistic_model.predict(x_test)

In [22]:
logistic_pred

array([1, 1, 0, ..., 0, 1, 0], shape=(5000,))

In [23]:
from sklearn.metrics import accuracy_score

In [24]:
logistic_score = accuracy_score(y_test, logistic_pred)

In [25]:
logistic_score

0.999

## Cross validation kodi

In [26]:
from sklearn.model_selection import cross_val_score, KFold

In [27]:
kn = KFold(n_splits=5, shuffle=True, random_state=42)
scores = cross_val_score(logistic_model, x,y,cv=kn, scoring="accuracy")
print(scores)

[0.9993 0.9987 0.9985 0.9987 0.9991]


In [28]:
import numpy as np
print(np.mean(scores).round(2))
np.std(scores)

1.0


np.float64(0.000293938769133949)

## Support Vektor Machine

In [29]:
from sklearn.svm import SVR

In [30]:
model = SVR(kernel="linear")

In [31]:
model

SVR(kernel='linear')

In [32]:
model.fit(x_train,y_train)

SVR(kernel='linear')

In [33]:
model

SVR(kernel='linear')

In [34]:
y_pred = model.predict(x_test) 

In [35]:
y_pred

array([ 0.78087978,  0.69212553, -0.18912201, ...,  0.12467149,
        0.71435011,  0.30916147], shape=(5000,))

In [36]:
y_pred_scores = (y_pred>= 0).astype(int)
print(accuracy_score(y_test, y_pred_scores))
score = accuracy_score(y_test, y_pred_scores)


0.54


In [37]:
score = accuracy_score(y_test, y_pred_scores)

In [38]:
print(scores)

[0.9993 0.9987 0.9985 0.9987 0.9991]


# K-Nearest Neighbours

In [39]:
from sklearn.neighbors import KNeighborsClassifier


In [40]:
modelknn = KNeighborsClassifier()


In [41]:
modelknn

KNeighborsClassifier()

In [43]:
modelknn.fit(x_train, y_train)

KNeighborsClassifier()

In [44]:
yy_preed = modelknn.predict(x_test)

In [45]:
yy_preed

array([1, 0, 0, ..., 0, 1, 0], shape=(5000,))

In [46]:
y

0        1
1        0
2        0
3        0
4        0
        ..
49995    1
49996    1
49997    1
49998    1
49999    0
Name: Sales_Classification, Length: 50000, dtype: int64

In [53]:
y_pred_prob = modelknn.predict_proba(x_test)
y_pred = np.argmax(y_pred_prob, axis=1)   # eng katta ehtimollikni klass sifatida oladi
score = accuracy_score(y_test, y_pred)


In [54]:
scoreknn = accuracy_score(y_test, y_pred)

In [55]:
scoreknn

0.882

In [59]:
kf = KFold(n_splits=5, shuffle = True, random_state=42)
scores = cross_val_score(modelknn,x,y,cv=kf, scoring="accuracy")
print(scores)

[0.8815 0.8828 0.8767 0.8822 0.8806]


In [60]:
print(np.mean(scores).round(3))

0.881


In [61]:
np.std(scores)

np.float64(0.00215833268983258)